version: '2'
services:

    nginx:
        build:
            context: .
            dockerfile: ./docker/Dockerfile
        ports:
            - "80:80"
        volumes:
            - ./www:/www
            - ./logs/nginx:/var/log/nginx
        depends_on:
            - db
            - fpm
        links:
            - fpm
        container_name: lvt_nginx
        networks:
            - lvt
        restart: unless-stopped

    fpm:
        build:
            context: .
            dockerfile: ./docker/Dockerfile-php
        ports:
            - "9050:9000"
        volumes:
            - ./www:/www
        volumes_from:
            - db
        container_name: lvt_fpm
        networks:
            - lvt
        restart: unless-stopped

    db:
        image: mysql:5.7.35
        command: --max_allowed_packet=32505856
        ports:
            - "33050:3306"
        volumes:
            - ./docker/db:/var/lib/mysql
            - /var/run/mysqld
        environment:
            MYSQL_ROOT_PASSWORD: secret
            MYSQL_USER: dbuser
            MYSQL_PASSWORD: secret
            MYSQL_DATABASE: app
        container_name: lvt_db
        networks:
            - lvt
        restart: unless-stopped

networks:
    lvt:
        driver: bridge
